### PR TITLE
Support private repo

### PR DESCRIPTION
**Pull request by JoHuang**
I defined REPO_TOKEN to support private repo.

### CODE REVIEW

**Comment by xadh00m** [comment]
Thank you for the PR. I would like to merge it.

Would you mind to use the arrow notation for the callbacks? And could you please elaborate why we need to ignore certificate checks on macos?

**Comment by JoHuang** [comment]
The callbacks are from the document of nodegit.
https://www.nodegit.org/guides/cloning/gh-two-factor/     #Clone options
If you thought it's better to change to arrow functions, I can modify them.

Also, you can check the "GitHub certificate issue in OS X" part in the same document.
I had to run servers with the workaround on my MacBook.

**Comment by xadh00m** [comment]
Thank you for the link. If you refactor the functions I´ll be glad to merge the feature.

**Comment by xadh00m** [comment]
Thanks!

**Pull request merged**
